version: "3.9"

services:
  # MySQL
  db:
    image: mysql:oracle
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes: [ "./:/var/www/html" ]
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wpsite

  # phpMyAdmnin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "81:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  db_data: {}
